sylius_resource:
    resources:
        bitbag_sylius_mollie_plugin.product_type:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusMolliePlugin\Entity\ProductType
                interface: BitBag\SyliusMolliePlugin\Entity\ProductTypeInterface
                form: BitBag\SyliusMolliePlugin\Form\Type\ProductTypeType
