sylius_grid:
    grids:
        bitbag_sylius_mollie_plugin_admin_product_type:
            driver:
                name: doctrine/orm
                options:
                    class: BitBag\SyliusMolliePlugin\Entity\ProductType
            fields:
                name:
                    type: string
                    label: sylius.ui.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
